---
platform: linux

inputs:
- name: snort-pulledpork-source
- name: snort-blobs-yml
- name: final-builds-dir-tarball
- name: releases-dir-tarball

outputs:
- name: finalized-release
- name: snort-bosh-source

run:
  path: snort-pulledpork-source/ci/tasks/update-release.sh
